title: "Connar Cybersecurity Portfolio"
description: "SOC Engineering • Detection • Threat Intel"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

minimal_mistakes_skin: "dark"

markdown: kramdown

sidebar:
  nav: "main"

nav:
  - title: "Home"
    url: /
  - title: "SOC Engineering"
    url: /SOC/

author:
  name: "Connar Ellington"
  bio: "Cybersecurity learner specialising in SOC engineering and offensive security."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/connar-ellington/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ConnarE92"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:connarellington@gmail.com"
